type = "webpack"
workers_dev = false
vars = { ENVIRONMENT = "stg" }

[site]
bucket = "./public"
entry-point = "./cloudflare"

[env.stg]
name = "biowasm-cdn-stg"
vars = { ENVIRONMENT = "stg" }
route = "cdn-stg.biowasm.com/*"
kv_namespaces = [
    { binding = "LOGS", id = "e76f7352461c4b82997961622b33e878" }
]

[env.prd]
name = "biowasm-cdn"
vars = { ENVIRONMENT = "prd" }
route = "cdn.biowasm.com/*"
kv_namespaces = [
    { binding = "LOGS", id = "d8adbc35772042248a89727658808f96" }
]
